### ISSUE TITLE
When rebooting, reboot message doesn't get deleted

### ISSUE THREAD

**Issue by mderveeuw** [mcndt/robotto-dj#5]
![Reboot Message](http://i.imgur.com/PTEWnif.png)

When using the "reboot" command, the bot reboots and send a message confirming the reboot, but that message doesn't get deleted.

**Comment by mcndt** [comment]
It can't delete the message because it's not there to delete it when rebooting, this would require it to check the chat logs after booting to find it,

**Comment by mderveeuw** [comment]
Working on a pull request
